import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Providers } from "@/context/providers";

const roboto = localFont({
  src: [
    {
      path: "./fonts/roboto-300.woff2",
      style: "normal",
      weight: "300",
    },
    {
      path: "./fonts/roboto-400.woff2",
      style: "normal",
      weight: "400",
    },
    {
      path: "./fonts/roboto-500.woff2",
      style: "normal",
      weight: "500",
    },
    {
      path: "./fonts/roboto-700.woff2",
      style: "normal",
      weight: "700",
    },
    {
      path: "./fonts/roboto-900.woff2",
      style: "normal",
      weight: "900",
    },
  ],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
